version: '3.9'

services:
  db:
    image: postgres:15
    container_name: nest_postgres
    restart: always
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_payments
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
